### PR TITLE
Update to latest snapshot of http4s-pac4j, monix and zio samples added

### PR DESCRIPTION
**Pull request by arixmkii**
Updates to support changes provided in https://github.com/pac4j/http4s-pac4j/pull/14

### CODE REVIEW

**Comment by leleuj** [comment]
@arixmkii I try to run the demo with `sbt clean compile run` to test the upgrade, but I get the following error:

```
[info] compiling 6 Scala sources to /Users/jleleu/sources/http4s-pac4j-demo/target/scala-2.13/classes ...
[error] /Users/jleleu/sources/http4s-pac4j-demo/src/main/scala/com/test/TestHttpApp.scala:26:41: Symbol 'type cats.effect.kernel.GenTemporal' is missing from the classpath.
[error] This symbol is required by 'method zio.interop.CatsEffectInstances.temporalRuntimeInstance'.
[error] Make sure that type GenTemporal is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'CatsEffectInstances.class' was compiled against an incompatible version of cats.effect.kernel.
[error] class TestHttpApp[F[_] <: AnyRef : Sync : ContextShift](blocker: Blocker, contextBuilder: (Request[F], Config) => Http4sWebContext[F]) {
[error]                                         ^
[error] /Users/jleleu/sources/http4s-pac4j-demo/src/main/scala/com/test/MainZIO.scala:16:14: Could not find an instance of Sync for zio.Task
[error]       Blocker[Task].use { b =>
[error]              ^
[error] /Users/jleleu/sources/http4s-pac4j-demo/src/main/scala/com/test/MainZIO.scala:17:33: Could not find an instance of ConcurrentEffect for zio.Task
[error]         BlazeServerBuilder[Task](global)
[error]                                 ^
[error] /Users/jleleu/sources/http4s-pac4j-demo/src/main/scala/com/test/TestHttpApp.scala:152:26: Could not find an instance of Sync for zio.Task
[error]     (request, config) => new Http4sWebContext[zio.Task](request, config.getSessionStore, runtime.unsafeRun(_))
[error]                          ^
[error] /Users/jleleu/sources/http4s-pac4j-demo/src/main/scala/com/test/TestHttpApp.scala:150:78: Could not find an instance of Sync for zio.Task
[error]   class ZIOApp(blocker: Blocker)(implicit runtime: zio.Runtime[Any]) extends TestHttpApp[zio.Task](
[error]                                                                              ^
[error] 5 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed 25 nov. 2021 à 16:26:27
```

**Comment by arixmkii** [comment]
@leleuj this line is really important
 https://github.com/pac4j/http4s-pac4j-demo/commit/82bcebd0266615959042280f8b35dd162917dd6b#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R38

Starting from 3.X this will require cats-effect 3, which is fully incompatible with older versions, which will require bumps for http4s version and removal on monix. 

I have plans to work on cats-effect 3 compatible version of pac4j-http4s, later, when I get some free time.

**Comment by arixmkii** [comment]
This latest commit https://github.com/pac4j/http4s-pac4j-demo/commit/f542c6774792350895250b3a4d3b63420a13930a broke it

**Comment by leleuj** [comment]
When reverting `zio-interop-cats` to version `3.1.1.0`, I have other dependency conflicts:

```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* co.fs2:fs2-core_2.13:3.0.3 (early-semver) is selected over {2.5.10, 2.5.10, 2.5.6}
[error] 	    +- dev.zio:zio-interop-cats_2.13:3.1.1.0              (depends on 3.0.3)
[error] 	    +- org.http4s:jawn-fs2_2.13:1.1.3                     (depends on 2.5.6)
[error] 	    +- org.http4s:http4s-core_2.13:0.22.7                 (depends on 2.5.10)
[error] 	    +- co.fs2:fs2-io_2.13:2.5.10                          (depends on 2.5.10)
[error]
[error] 	* org.typelevel:cats-effect_2.13:3.1.1 (early-semver) is selected over {2.5.1, 2.5.1, 2.5.4, 2.0.0, 2.5.1, 2.5.1}
[error] 	    +- co.fs2:fs2-core_2.13:3.0.3                         (depends on 3.1.1)
[error] 	    +- org.typelevel:vault_2.13:2.1.13                    (depends on 2.5.1)
[error] 	    +- org.typelevel:unique_2.13:2.1.5                    (depends on 2.5.1)
[error] 	    +- org.specs2:specs2-cats_2.13:4.10.0                 (depends on 2.0.0)
[error] 	    +- org.http4s:http4s-core_2.13:0.22.7                 (depends on 2.5.4)
[error] 	    +- io.monix:monix-catnap_2.13:3.4.0                   (depends on 2.5.1)
[error] 	    +- com.comcast:ip4s-core_2.13:2.0.4                   (depends on 2.5.1)
```

Would you mind taking a closer look and ensure the demo starts? Thanks

**Comment by arixmkii** [comment]
@leleuj revert it to what was in my commit
```
"dev.zio" %% "zio-interop-cats" % "2.5.1.0"
```
I tried it on a clean clone and was able to run demo.

**Comment by leleuj** [comment]
OK. The demo starts this way.

I tested the IO one, but the click on the "Protected url by SAML2: /saml2" link does not seem to work: I land on a blank page instead of being redirected to Okta... Maybe the SAML form is not automatically posted...

**Comment by arixmkii** [comment]
Will check SAML tomorrow. I only checked form and OIDC, because we have them in our real apps.

**Comment by arixmkii** [comment]
In SAML case it is redirecting using HTTP 200 + JS or user action (btn click). But Http4s response for Ok isn't rendering body. Need to update the code. Will create PR with fix.

**Comment by arixmkii** [comment]
@leleuj  PR provided https://github.com/pac4j/http4s-pac4j/pull/15

**Comment by leleuj** [comment]
Thanks for the fix. I just released the version 3. It will show up in the Maven central repository in a few minutes.

**Pull request merged**
